### ISSUE TITLE
Exception by SmartResizePolicy if table.isTableMenuButtonVisible is enabled

### ISSUE THREAD

**Issue by jansorg** [edvin/tornadofx#606]
I'm using a `treetableview` and have set the property `isTableMenuButtonVisible` to true.
When I hide/show one of the columns, the SmartResizePolicy throws an exception.

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at tornadofx.SmartResizeKt$resizeColumnsToFitContent$doResize$1.invoke(SmartResize.kt:366)
	at tornadofx.SmartResizeKt$resizeColumnsToFitContent$doResize$1.invoke(SmartResize.kt)
	at tornadofx.SmartResizeKt.resizeColumnsToFitContent(SmartResize.kt:374)
	at tornadofx.SmartResizeKt.resizeColumnsToFitContent$default(SmartResize.kt:361)
	at tornadofx.SmartResizeKt.resizeCall(SmartResize.kt:412)
	at tornadofx.TreeTableSmartResize.call(SmartResize.kt:122)
	at tornadofx.TreeTableSmartResize.call(SmartResize.kt:120)
	at javafx.scene.control.TreeTableView.updateVisibleLeafColumns(TreeTableView.java:1908)
	at javafx.scene.control.TreeTableView.lambda$new$117(TreeTableView.java:816)
	at javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at com.sun.javafx.binding.BidirectionalBinding$BidirectionalBooleanBinding.changed(BidirectionalBinding.java:264)
	at com.sun.javafx.binding.BidirectionalBinding$BidirectionalBooleanBinding.changed(BidirectionalBinding.java:227)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.scene.control.CheckMenuItem.setSelected(CheckMenuItem.java:132)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1394)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.sun.javafx.scene.control.skin.TreeTableViewSkin.resizeColumnToFitContent(TreeTableViewSkin.java:346)
	... 59 more

```

**Comment by edvin** [comment]
Hi! This has been reported several times earlier, and in every case it has been because one or more table columns don't have a defined header label value. This is required for the JavaFX function `TreeTableViewSkin.resizeColumnToFitContent()` to run correctly. Please verify this. If that doesn't solve your problem, can you post a minimal sample app that showcases the issue?

**Comment by jansorg** [comment]
@edvin Thanks for the reply!
Here's an example to reproduce this. As soon as I hide two columns the exception ocurrs.
I'm running this with Kotlin 1.2.21, Java 1.8_162 and tornadofx 1.7.14.

```kotlin
package eu.jadev

import javafx.application.Application
import javafx.scene.control.TreeItem
import tornadofx.*

class MyApp : App(TreeTableView::class)

class TreeTableView : View() {
    private val rootnode: TreeItem<String> = TreeItem("root node")
    init {
        rootnode.children.add(TreeItem("child"))
    }

    override val root = treetableview(rootnode) {
        isTableMenuButtonVisible = true
        smartResize()

        column<String,String>("Name 1", { it.value.value.toProperty() })
        column<String,String>("Name 2", { it.value.value.toProperty() })
        column<String,String>("Name 3", { it.value.value.toProperty() })
    }
}

fun main(args: Array<String>) {
    Application.launch(MyApp::class.java, *args)
}
```

**Comment by edvin** [comment]
Perfect, thanks! I was able to solve the problem by not calling resize for hidden columns. The same bug applied to TableView, so that's fixed now as well. I've pushed a new snapshot to sonatype if you want to try it out.

**Comment by jansorg** [comment]
@edvin Thanks!
Hiding is working now. 
Showing the hidden columns again is still throwing that exception, though...

**Comment by edvin** [comment]
I've committed another fix. When you change a column, the skin is in a state where resize just can't run, so I'm simply catching that error now.

**Comment by jansorg** [comment]
@edvin Thanks! I'll test with the next snapshot :)

**Comment by kururu-abdo** [comment]
am using intellij idea 2018.2
tornadofx 1.7.17
kotlin 1.2.51

class myview: View("basic"){

override val root= hbox{
label("hello world"){
}


}


}

but this problem arises 
java.lang.Reflection.InvocationTargetException   


help me please 
am beginner in tornadofx

**Comment by edvin** [comment]
@kururu-abdo Don't hijack other issues :) Create a new issue for your problem, including the complete code and complete stack trace showing the issue. Also include your Java version.

**Comment by kururu-abdo** [comment]
ok
